#[global.tls]
#certs = "/path/to.certs.pem"
#key = "/path/to/key.pem"

[development]
address = "127.0.0.1"
port = 8000
workers = 16
keep_alive = 8
log = "normal"
#secret_key = ""
limits = { forms = 32768 }
template_dir = "src/templates/"

[staging]
address = "127.0.0.1"
port = 8001
workers = 16
keep_alive = 8
log = "normal"
#secret_key = ""
limits = { forms = 32768 }
template_dir = "src/templates/"

[production]
address = "0.0.0.0"
port = 8090
workers = 32
keep_alive = 16
#log = "normal"
#secret_key = ""
limits = { forms = 32768 }
template_dir = "src/templates/"

[global.databases.rocket_demo]
url = "mysql://root:password@127.0.0.1/rocket_demo"
