#[global.tls]
#certs = "/path/to.certs.pem"
#key = "/path/to/key.pem"

[development]
address = "127.0.0.1"
port = 8000
workers = 16
keep_alive = 5
log = "normal"
#secret_key = ""
limits = { forms = 32768 }
template_dir = "src/templates/"

[staging]
address = "127.0.0.1"
port = 8000
workers = 16
keep_alive = 5
log = "normal"
#secret_key = ""
limits = { forms = 32768 }
template_dir = "src/templates/"

[production]
address = "127.0.0.1"
port = 8000
workers = 16
keep_alive = 5
log = "normal"
#secret_key = ""
limits = { forms = 32768 }
template_dir = "src/templates/"
